M48
; DRILL file {KiCad 9.0.6} date 2026-05-22T12:10:39+0530
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2026-05-22T12:10:39+05:30
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.6
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C2.100
%
G90
G05
T1
X128.69Y-120.84
X129.29Y-78.3
X170.7Y-77.7
X171.88Y-120.62
M30
